main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>', views.event_detail, name='event-detail'),
   # path('delete-event/<int:id>', views.event_delete, name='event-delete'),
    path('new-event', views.event_add, name='event-add'),
    path('join-event/<int:id>', views.event_join, name='event-join'),
]

story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from datetime import datetime

# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db import models

# Create your models here.
class Attendee(models.Model):
    
    name = "Attendee"
    
    nama = models.CharField(max_length=50, unique=True)
    
    class Meta:
        verbose_name = "Attendee"
        verbose_name_plural = "Attendees"

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        return reverse("Attendee_detail", kwargs={"pk": self.pk})


class Event(models.Model):
    
    name = "Event"

    nama = models.CharField(max_length=50)
    deskripsi = models.TextField(max_length=500)
    lokasi = models.CharField(max_length=50, default="Anywhere")
    nama_penyelenggara = models.CharField(max_length=100)
    tanggal = models.CharField(
        max_length=50, default=datetime.now().strftime("%H:%M %d-%m-%Y"))
    peserta = models.ManyToManyField(Attendee, blank=True)

    waktu_dibuat= models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Event_detail", kwargs={"pk": self.pk})

main/forms.py
from django import forms
from .models import Event, Attendee
from crispy_forms.helper import FormHelper
from datetime import datetime

class EventForm(forms.ModelForm):
    
    def clean_tanggal(self):
        data = self.cleaned_data["tanggal"]
        if data == "Anytime": return data
        try:
            data = datetime.strptime(data, '%H:%M %d-%m-%Y')
        except:
            raise forms.ValidationError(
                u'Tanggal/waktu anda tidak valid!! "%s"' % data)
        
        if datetime.now() >= data:
            raise forms.ValidationError(u'Tanggal/waktu anda tidak valid!! "%s"' % data)
        return data
        
    class Meta:
        model = Event
        fields = "__all__"
        widgets = {
            'tanggal' : forms.DateTimeInput(),
            'peserta': forms.HiddenInput()
        }

class AttendeeForm(forms.ModelForm):
    class Meta:
        model = Attendee
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect
from .forms import EventForm, AttendeeForm
from .models import Event, Attendee

def home(request):
    context = {
        'events' : Event.objects.all()
    }
    return render(request, 'main/home.html', context=context)

def event_detail(request, id):
    """
    Event Detail
    """
    context = {
        'event' : Event.objects.get(id=id)
    }
    return render(request, 'main/detail-event.html', context=context)


def event_join(request, id):
    if request.method == "POST":
        event = Event.objects.get(id=id)
        nama = request.POST["nama"].strip()
        new, status = Attendee.objects.get_or_create(nama=nama)
        if status:
            new.save()
            event.peserta.add(new)
        else:
            try:
                event.peserta.get(nama=nama)
            except:
                event.peserta.add(new)
        return redirect('main:home')
    
    else:
        context = {
            'form' : AttendeeForm(),
        }
        return render(request, 'main/join-event.html', context=context)

def event_add(request):
    context = {
        'form': EventForm(),
    }
    
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:home')
        context['form'] = form
        return render(request, 'main/new-event.html', context=context)
    else:
        return render(request, 'main/new-event.html', context=context)

main/templates/main/detail-event.html
{% load static %}

  {% block head %}
  <title>EVENTZ</title>
  <meta name="description" content="Events around you">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="EVENTZ">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="EVENTZ">

  <link rel="icon" type="image/x-icon" href="{% static 'img/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}
  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="EVENTZ">EVENTZ</a>
        </nav>
        
        <div class ="canvas">
            <h1>{{ event.nama }}</h1>
            <table>
                <tr>
                <th>Lokasi</th>
                <th>: </th>
                <td>{{ event.lokasi }}</td>
                </tr>
                <tr>
                <th>Penyelenggara</th>
                <th>: </th>
                <td>{{ event.nama_penyelenggara }}</td>
                </tr>
                <tr>
                <th>Tanggal</th>
                <th>: </th>
                <td>{{ event.tanggal }}</td>
                </tr>
                <tr>
            </table>

            <h1>Deskripsi</h1>
            <p>{{ event.deskripsi }}</p>

            <h1>Peserta</h1>
            {% if event.peserta.count == 0 %}
            <p>Belum ada peserta</p>
            {% else %}
            <ul>
            {% for peserta in event.peserta.all %}
              <li>{{ peserta.nama }}</li>
            {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="tambah-jadwal">
                <a href="{% url 'main:home' %}"><div class="round-button button-accent">Kembali</div></a>
                <a href="{% url 'main:event-join' event.id %}"><div class="round-button button-accent join">Ikut</div></a>
            </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

main/templates/main/home.html
{% load static %}

  {% block head %}
  <title>EVENTZ</title>
  <meta name="description" content="Events around you">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="EVENTZ">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="EVENTZ">

  <link rel="icon" type="image/x-icon" href="{% static 'img/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
    <div class="grid grid-card">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="EVENTZ">EVENTZ</a>
        </nav>
        
        <div class ="canvas">
            <div class="tambah-jadwal">
                <a href="{% url 'main:event-add' %}"><div class="round-button button-accent">+ Jadwal Baru</div></a>
            </div>

            <div class="deck">
                <div class="deck-grid">
                    <ul>
                      {% for event in events %}
                        <a href="{% url 'main:event-detail' event.id %}">
                          <li>
                              <h1>{{ event.nama }}</h1>
                              <code class="small">{{ event.tanggal }}</code> </br>
                              <code class="small">{{ event.lokasi }}</code>

                              {% if 0 < event.peserta.count <= 3 %} 
                                <p>
                                {{ event.peserta.count }} peserta:</br>
                                {% for peserta in event.peserta.all|slice:"::-1"|slice:":3" %}
                                 - {{ peserta.nama }}</br>
                                {% endfor %}
                                </p>
                              {% endif %}

                              {% if event.peserta.count > 3 %}
                              <p>
                                  dan lainnya ...
                              </p>
                              {% endif %}
                          </li>
                        </a>  
                      {% endfor %}
                    </ul>
                </div>
            </div>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

main/templates/main/join-event.html
{% load static %}
{% load crispy_forms_tags %}

  {% block head %}
  <title>EVENTZ</title>
  <meta name="description" content="Events around you">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="EVENTZ">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="EVENTZ">

  <link rel="icon" type="image/x-icon" href="{% static 'img/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="EVENTZ">EVENTZ</a>
        </nav>

        <div class="canvas">

          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit">Submit</button>
          </form>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

main/templates/main/new-event.html
{% load static %}
{% load crispy_forms_tags %}

  {% block head %}
  <title>EVENTZ</title>
  <meta name="description" content="Events around you">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="EVENTZ">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="EVENTZ">

  <link rel="icon" type="image/x-icon" href="{% static 'img/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="EVENTZ">EVENTZ</a>
        </nav>

        <div class="canvas">

          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit">Submit</button>
          </form>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block head %}
    {% endblock head %}

    {% block script %}
    {% endblock script %}

    {% block style %}
    {% endblock style %}


    {% block body %}
    {% endblock body %}

        {% block main %}
        {% endblock main %}


</html>

templates/navigation.html
<style>
.bridge {
  position: relative;
  z-index: 99;
  font-family: 'Open Sans', sans-serif;;
}
.bridge-back {
  width: 100px;
  padding-top: 5px;
  padding-bottom: 5px;
  text-align: center;
  color: #000;
  text-transform: uppercase;
  font-weight: 600;
  margin-left: 30px;
  margin-bottom: 30px;
  cursor: pointer;
  display: inline-block;
  position: fixed;
  z-index: 999;
  top: 23px;
  left: -5px;
}

.bridge-accent {
  background: linear-gradient(300deg, rgba(240,147,251,1) 0%,   rgba(245,87,108,1) 100%);
  border-radius: 100px;
  -webkit-transition: all .15s ease-in-out;
  transition: all .15s ease-in-out;
  color: #fff;
}
.bridge-accent:hover {
  filter: drop-shadow(0 5px 5px rgb(0,0,0,0.5));
  transform: translate(0px, -2px);
}
</style>


<div class="bridge">
  <a href="{% url 'bridge:bridge' %}"><div class="bridge-back bridge-accent">← Back</div></a>
</div>


<script>
var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
  var currentScrollPos = window.pageYOffset;
  if (prevScrollpos > currentScrollPos) {
    document.getElementsByClassName("bridge-back")[0].style.top = "30px";
  } else {
    document.getElementsByClassName("bridge-back")[0].style.top = "-60px";
  }
  prevScrollpos = currentScrollPos;
}
</script>